AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  civitas-backend

  Civitas Application Backend

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: staging

  ProfileHandler:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/profile/
      Handler: profile
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /profiles
            Method: ANY
            RestApiId:
              Ref: ApiGatewayApi

  MatchHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/match/
      Handler: match
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /matches
            Method: ANY
            RestApiId:
              Ref: ApiGatewayApi

  StandingHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/standing/
      Handler: standing
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /standings
            Method: ANY
            RestApiId:
              Ref: ApiGatewayApi

  LeagueHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/league/
      Handler: league
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /leagues
            Method: ANY
            RestApiId:
              Ref: ApiGatewayApi
  NewsHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/news/
      Handler: news
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /news
            Method: ANY
            RestApiId:
              Ref: ApiGatewayApi

  WinnerlistHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/winnerlist/
      Handler: winnerlist
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /winnerlists
            Method: ANY
            RestApiId:
              Ref: ApiGatewayApi

  DivisionHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/division/
      Handler: division
      Runtime: go1.x
      Policies: AmazonDynamoDBFullAccess
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /division
            Method: ANY
            RestApiId:
              Ref: ApiGatewayApi
